const profile: string =
  "学生時代は明治大学大学院先端数理科学研究科の博士前期課程に在籍し，HCI（ヒューマンコンピュータインタラクション）の分野を研究\n\
主に初心者の運転支援や，手書き文字練習の支援，スマートフォン利用時の姿勢矯正に関する研究に着手\n\
また，ソフトウェアエンジニアとしてプログラミングスキルを活かしシステム開発にも着手\n\
主にwebアプリケーションの開発に携わり，フロントエンド，バックエンド，インフラなど幅広く経験\n\
";
const hobbies: string[] = [
  "ドラム",
  "サッカー",
  "卓球",
  "スポーツ観戦",
  "邦ロック",
  "J-POP",
  "謎解き",
  "ルービックキューブ",
];
const career: { year: string; content: string }[] = [
  { year: "2020/03", content: "明治大学付属明治高等学校卒業" },
  {
    year: "2020/04",
    content: "明治大学総合数理学部先端メディアサイエンス学科入学",
  },
  {
    year: "2024/03",
    content: "明治大学総合数理学部先端メディアサイエンス学科卒業",
  },
  {
    year: "2024/04",
    content: "明治大学大学院先端数理科学研究科先端メディアサイエンス専攻入学",
  },
  {
    year: "2026/03",
    content:
      "明治大学大学院先端数理科学研究科先端メディアサイエンス専攻卒業，修士（工学）取得",
  },
  {
    year: "2026/04",
    content: "LINEヤフー株式会社に入社",
  },
];

const skills = [
  "git",
  "github",
  "githubactions",
  "vscode",
  "linux",
  "bash",
  "nginx",
  "mysql",
  "postgresql",
  "unity",
  "cs",
  "java",
  "maven",
  "processing",
  "arduino",
  "php",
  "html",
  "css",
  "js",
  "ts",
  "npm",
  "pnpm",
  "nodejs",
  "jest",
  "vite",
  "react",
  "nextjs",
  "sequelize",
  "prisma",
  "vue",
  "nuxtjs",
  "pinia",
  "svelte",
  "angular",
  "p5js",
  "vuetify",
  "materialui",
  "sass",
  "python",
  "anaconda",
  "tensorflow",
  "django",
  "fastapi",
  "opencv",
  "sklearn",
  "go",
  "docker",
  "firebase",
  "nestjs",
  "express",
  "latex",
];

export const skillNameMap: Record<string, string> = {
  git: "Git",
  github: "GitHub",
  githubactions: "GitHub Actions",
  vscode: "VS Code",
  linux: "Linux",
  bash: "Bash",
  nginx: "Nginx",
  mysql: "MySQL",
  postgresql: "PostgreSQL",
  unity: "Unity",
  cs: "C#",
  java: "Java",
  maven: "Maven",
  processing: "Processing",
  arduino: "Arduino",
  php: "PHP",
  html: "HTML",
  css: "CSS",
  js: "JavaScript",
  ts: "TypeScript",
  npm: "npm",
  pnpm: "pnpm",
  nodejs: "Node.js",
  jest: "Jest",
  vite: "Vite",
  react: "React",
  nextjs: "Next.js",
  sequelize: "Sequelize",
  prisma: "Prisma",
  vue: "Vue.js",
  nuxtjs: "Nuxt.js",
  pinia: "Pinia",
  svelte: "Svelte",
  angular: "Angular",
  p5js: "p5.js",
  vuetify: "Vuetify",
  materialui: "Material UI",
  sass: "Sass",
  python: "Python",
  anaconda: "Anaconda",
  tensorflow: "TensorFlow",
  django: "Django",
  fastapi: "FastAPI",
  opencv: "OpenCV",
  sklearn: "scikit-learn",
  go: "Go",
  docker: "Docker",
  firebase: "Firebase",
  nestjs: "NestJS",
  express: "Express",
  latex: "LaTeX",
};

export { career, hobbies, profile, skills };
